
spring.threads.virtual.enabled=true

# Ollama 配置
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen:4b
langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true

# 阿里云千问API配置
#langchain4j.open-ai.chat-model.api-key=${ALI_QWEN_LLM_API_KEY}
#langchain4j.open-ai.chat-model.base-url=${ALI_QWEN_LLM_BASE_URL}
#langchain4j.open-ai.chat-model.model-name=qwen-plus
# 火山引擎
langchain4j.open-ai.chat-model.api-key=${HUO_SHAN_API_KEY}
langchain4j.open-ai.chat-model.base-url=${HUO_SHAN_OPEN_AI_BASE_URL}
langchain4j.open-ai.chat-model.model-name=${HUO_SHAN_MODEL}

langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

# 阿里云千问
#langchain4j.open-ai.streaming-chat-model.api-key=${ALI_QWEN_LLM_API_KEY}
#langchain4j.open-ai.streaming-chat-model.base-url=${ALI_QWEN_LLM_BASE_URL}
#langchain4j.open-ai.streaming-chat-model.model-name=qwen-plus

# 火山引擎
langchain4j.open-ai.streaming-chat-model.api-key=${HUO_SHAN_API_KEY}
langchain4j.open-ai.streaming-chat-model.base-url=${HUO_SHAN_OPEN_AI_BASE_URL}
langchain4j.open-ai.streaming-chat-model.model-name=${HUO_SHAN_MODEL}

langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true

#langchain4j.open-ai.chat-model.temperature=0.7
#langchain4j.open-ai.chat-model.timeout=60s
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true


logging.level.dev.langchain4j=DEBUG

management.endpoints.web.exposure.include=*
# 禁用追踪采样，避免Zipkin连接错误
management.tracing.sampling.probability=0

# 禁用Zipkin导出
management.zipkin.tracing.enabled=false
management.otlp.tracing.enabled=false


#langchain4j.http.clientBuilderFactory=dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory
